events {}
http {
  server {
    listen 8080;
    location /rest/v1/ {
      proxy_pass http://postgrest:3000/;
      proxy_read_timeout 20s;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Content-Type $http_content_type;
      proxy_set_header Accept $http_accept;
      proxy_set_header Prefer $http_prefer;
    }
  }
}
